name: Arch Linux sync repository to AUR action
description: GitHub Action to sync a given repository to the AUR.
author: callmetango

inputs:
  repository:
    description: |
      The name of the GitHub repository to work on in the form [HOST/]OWNER/REPO.
      It defaults to the repository where the workflow is run.
  aur-repository:
    description: |
      The name of the AUR repository. It defaults to the name of the GitHub repository.
  ssh-private-key:
    description: The SSH private key to use when connecting to the AUR
    type: string
    required: true

  ssh-key-fingerprints:
    description: The SHA256 fingerprints of the AUR SSH host keys
    type: string
    default: |
      ed25519: SHA256:RFzBCUItH9LZS0cKB5UE6ceAYhBD5C8GeOBip8Z11+4
      ecdsa: SHA256:uTa/0PndEgPZTf76e1DFqXKJEXKsn7m9ivhLQtzGOCI
      rsa: SHA256:5s5cIyReIfNNVGRFdDbe3hdYiI5OelHGpw2rOUud3Q8

runs:
  using: composite
  steps:
    - shell: sh
      env:
        SCRIPTS_PATH: ${{ github.action_path }}/scripts
        # composite actions do not auto-export INPUT_* :-/
        INPUT_AUR_REPOSITORY: ${{ inputs.aur-repository }}
        _REPO: ${{ inputs.repository || github.repository }}
      run: |
        # Set up environment
        set -u
        chmod u+x "$SCRIPTS_PATH"/*.sh
        . "$SCRIPTS_PATH"/gh-helpers.sh

        gh_env_set REPOSITORY "$_REPO"
        gh_env_set AUR_REPOSITORY "${INPUT_AUR_REPOSITORY:-${_REPO##*/}}"
        gh_env_set SCRIPTS_PATH "$SCRIPTS_PATH"
        
        mkdir -m 0700 -p ~/.ssh
        printf '${{ inputs.ssh-key-fingerprints }}' > ~/.ssh/aur-fingerprints

    - shell: sh
      run: |
        # Verify AUR SSH host key fingerprints
        "$SCRIPTS_PATH"/verify-ssh-fingerprints.sh \
            aur.archlinux.org ~/.ssh/aur-fingerprints ~/.ssh/known_hosts
        
    - shell: sh
      run: |
        # Sync repository to AUR
        set -u
        
        eval $(ssh-agent)
        printf '%s\n' '${{ inputs.ssh-private-key }}' | tr -d '\r' | ssh-add -
        
        cd "$HOME"
        mkdir sync-repo && cd sync-repo

        git config set --global advice.defaultBranchName false
        git init .
        git remote add origin "$GITHUB_SERVER_URL"/"$REPOSITORY"
        git remote add aur ssh://aur@aur.archlinux.org/"$AUR_REPOSITORY".git
        git remote -v

        git fetch origin
        BRANCH=$(git symbolic-ref --short HEAD) # get default branch
        echo "BRANCH: $BRANCH"
        git push aur "origin/$BRANCH:refs/heads/$BRANCH"
