name: Arch Linux bump package version action
description: GitHub Action to bump the version of a PKGBUILD.
author: callmetango

inputs:
  ssh-private-key:
    description: The SSH private key to use when connecting to the AUR
    type: string
    required: true

  ssh-key-fingerprints:
    description: The SHA256 fingerprints of the AUR host SSH keys
    type: string
    default: |
      ed25519: SHA256:RFzBCUItH9LZS0cKB5UE6ceAYhBD5C8GeOBip8Z11+4
      ecdsa: SHA256:uTa/0PndEgPZTf76e1DFqXKJEXKsn7m9ivhLQtzGOCI
      rsa: SHA256:5s5cIyReIfNNVGRFdDbe3hdYiI5OelHGpw2rOUud3Q8

runs:
  using: composite
  steps:
    - name: Set up environment
      shell: sh
      run: |
        mkdir -m 0700 -p ~/.ssh
        
        eval $(ssh-agent)
        printf '${{ inputs.ssh-private-key }}\n' | tr -d '\r' | ssh-add -
        
        #ssh-keygen -y -f bot@aur.archlinux.org > bot@aur.archlinux.org.pub
        
        printf '${{ inputs.ssh-key-fingerprints }}' > ~/.ssh/aur-fingerprints

    - name: Verify AUR SSH key fingerprints
      shell: sh
      run: |
        sh "$GITHUB_ACTION_PATH"/scripts/verify-ssh-fingerprints.sh \
           aur.archlinux.org ~/.ssh/aur-fingerprints ~/.ssh/known_hosts
        
    - name: Sync to AUR
      shell: sh
      run: |
        echo "Syncing..."
        ssh aur@aur.archlinux.org help
